### ISSUE TITLE
compiled program fails to launch

### ISSUE THREAD

**Issue by baboomerang** [integralfx/SPDEditor#1]
Hey, I compiled this program from source and the resulting jar file fails to run.
```
kotlinc SPDEditorGUI.kt SPDEditor.kt XMP.kt -include-runtime -d SPDEditorGui.jar
```  
Compiles successfully but when executing the jar I get this:

```
$ java -jar SPDEditorGui.jar
no main manifest attribute, in SPDEditorGui.jar
```

**Comment by integralfx** [comment]
You just need to add `Main-Class: SPDEditorGUI` in the MANIFEST.MF file in the jar.
