### ISSUE TITLE
SPDEditor fails to save base frequency.

### ISSUE THREAD

**Issue by AreYouLoco** [integralfx/SPDEditor#2]
I have dumped my SPD EEPROM from the system and I would like to edit base frequency from 933.33 to 1067.24 and when I change that and click on SET and save the file. After opening the file again the base frequency is still 933.33. What might be wrong?

Just to make it straight other timing values and supported CLs are saved.

**Comment by integralfx** [comment]
Can you send your SPD dump?

**Comment by AreYouLoco** [comment]
https://mega.nz/folder/mr5FFSpT#GtnJfrwia8tyViZbJTOwlg
Two dumps for two of my dimms. The sticks are Hynix HyperX DDR3L 1866MT/s 8GB.

**Comment by integralfx** [comment]
You need to press enter when changing the frequency. Just of limitation of Java textboxes. 

Set is for applying the timings.

[spd_dumps_1066.zip](https://github.com/integralfx/SPDEditor/files/7684085/spd_dumps_1066.zip)

**Comment by AreYouLoco** [comment]
Ok thanks. But my SPD region is locked anyway and I have to write XMP in order to overclock.
